### PR TITLE
styles.css: Correct font URL

### PR DESCRIPTION
**Pull request by davelab6**
The URLs inside a stylesheet are relative to the URL of the stylesheet. So in the below, the fonts URL is `/stylesheets/type/Family-Style.ext`. 

screen shot 2015-09-07 at 19 02 06

### CODE REVIEW

**Comment by jonpinhorn** [comment]
Hi Dave, 

I’ve done that now. I have also moved the ‘type’ folder into the stylesheets folder but still no luck?

Sorry about this.

JP

**Comment by davelab6** [comment]
You moved the type folder into `/stylesheets` so this pull request is no longer a valid fix, but you also updated the styles.css to point to `stylesheets/type/fontfile.otf` which is incorrect in another way; because the styles.css file is already in the stylesheets directory, this means the file is being requested from `stylesheets/stylesheets/type/fontfile.otf`

**Comment by jonpinhorn** [comment]
Thanks for you patience. It’s working now. :-)

**Comment by davelab6** [comment]
:dart:

**Comment by jonpinhorn** [comment]
Having got it working I updated my web format font files and now it’s broken again?

**Comment by davelab6** [comment]
In
https://github.com/jonpinhorn/shrikhand/commit/6d2b02e80ae62eaca5e611d95ac513d9daa26be0
you updated the CSS again to its previous broken state

**Comment by jonpinhorn** [comment]
Dave, 

My half and rakar forms work on Chrome via my website but not via GH pages; any idea why?

Thanks, 

JP

**Comment by davelab6** [comment]
On 9 September 2015 at 05:50, Jon Pinhorn notifications@github.com wrote:

> My half and rakar forms work on Chrome via my website but not via GH
> pages; any idea why?

Hmm that is strange. What are the 2 URLs you are comparing?

**Pull request closed without merging**
